### ISSUE TITLE
Text Styles fail to be imported

### ISSUE THREAD

**Issue by raulfunkie** [sketch-hq/fig2sketch#102]
When importing a Figma file into Sketch, some errors appear and the Text Styles within the Imported File are not imported as Text Styles in Sketch.

Screenshot of the error:
![dccd7f9d403f6d3c63c4bb34eea5522b52f8c787](https://github.com/sketch-hq/fig2sketch/assets/15929687/7c727f75-d444-42e2-8869-2942ada82a49)

File used
- [Shopify’s Polaris Styles](https://www.figma.com/community/file/1111359207966840858)

**Comment by tmdvs** [comment]
Note: This is expected. Currently, `fig2sketch` will only download a font family if it's available on Google Fonts.
