### ISSUE TITLE
The colorspace of the imported Figma document is always sRGB, even if the source Figma document is P3

### ISSUE THREAD

**Issue by rustyshelf** [sketch-hq/fig2sketch#113]
If I run the command line tool on a figma file which has its colorspace set to DisplayP3 I can see that it exists in the `--dump-fig-json` output:
```
"documentColorProfile": "DISPLAY_P3"
```

However the resulting Sketch `document.json` that is created from this file has:
```
"colorSpace": 1,
```

This is sRGB, which is the wrong colorspace. This appears to be because the colorspace conversion is hard coded here: https://github.com/sketch-hq/fig2sketch/blob/baa4b843a6d287a2671a3f1f0eddb35b632ac734/src/converter/document.py#L26

I feel like if you're converting design documents, this is a fairly important thing to include? I do understand that fig2sketch probably pre-dates Sketch's support for colorspaces though.

**Comment by tmdvs** [comment]
Thanks for taking the time to report this @rustyshelf 🙇‍♂️

You're correct in the assumption that `fig2sketch` first shipped before Figma shipped support for the P3 colour space. However, you quite rightly point out that colour space is an important component of design documents. 

Consider this on our Radar.
