### ISSUE TITLE
Unrecognized section

### ISSUE THREAD

**Issue by Shilem** [sketch-hq/fig2sketch#60]
After the conversion, the frame in the Figma section cannot be converted, and it is displayed as empty in the sketch file

**Comment by javitonino** [comment]
Hi!

Sections were recently added and we have not had the chance to add support yet. We are working on it and should have basic support ready soon: https://github.com/sketch-hq/fig2sketch/pull/63

Thanks for your report!

**Comment by esloho** [comment]
We just released a new version with this change, [v0.1.5](https://github.com/sketch-hq/fig2sketch/releases/tag/v0.1.5), check it out!

You can also install it now from pip directly if that's more convenient for you! You can just run:

 `pip install fig2sketch[fast]`  

Thanks for the issue! ✨
